Auth-Api docs
lambdalabs-eu1-webchat/webchat-backend pull request #39
Opened 2019-05-01 14:34 UTC by sampler36

# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please add a relevant label.

## Change status

- [ ] Complete, tested, ready to review and merge

- [ ] Complete, but not tested (may need new tests)

- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe steps taken to ensure this feature is functional and does not break other features:

# Checklist:

- [ ] My code follows the style guidelines of this project

- [ ] I have performed a self-review of my own code

- [ ] I have commented my code, particularly in hard-to-understand areas

- [ ] I have made corresponding changes to the documentation, if relevant

- [ ] I have run the app using my feature and ensured that no functionality is broken

- [ ] My changes generate no new warnings

- [ ] There are no merge conflicts

2019-05-01 15:30 UTC, sampler36 commented
Resolved #39

2019-05-01 18:32 UTC, Pav0l requested changes
Good job with the docs @sampler36 ! 🔥 

Had couple of comments below:

2019-05-01 18:32 UTC, Pav0l commented on routes/endpoint-docs/authDocs.js
> + *        "email": "nicolasgroup@gmail.com"
please add to request example:
```
"hotel_id": "5cc74ab1f16ec37bc8cc4cdb",
"motto": "Cross-platform executive application",
 "user_type": "receptionist"
```

2019-05-01 18:32 UTC, Pav0l commented on routes/endpoint-docs/authDocs.js
> + *
Success response has this format:
```
{
    "user": {
        "_id": "5cc9b28740daa6367c5d0283",
        "hotel_id": "5cc74ab1f16ec37bc8cc4cdb",
        "name": "blabla",
        "email": "aazzaa@hotmail.com",
        "motto": "Cross-platform executive application",
        "user_type": "receptionist",
        "__v": 0
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmxhYmxhIiwiaG90ZWxfaWQiOiI1Y2M3NGFiMWYxNmVjMzdiYzhjYzRjZGIiLCJpYXQiOjE1NTY3MjIzMTF9.zI9RKAe7Gr8kfctrMH_51ixu2P0v6yNQXhPZfwo6m8I"
}
```

2019-05-02 07:50 UTC, Pav0l approved these changes

2019-05-02 07:59 UTC, merged